#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

usage="Usage: editor <send|recv>"

if [ $# -lt 1 ]; then
  echo "$usage"
  exit 1
fi

case "$1" in
  send)
    tmp=$(mktemp 2> /dev/tty)
    mv "$tmp" "$tmp.jsonc"
    tmp="$tmp.jsonc"

    {
      printf "// Copy this value and send it to your peer over a secure channel:\n\n"
      cat -
      printf "\n\n// Then close the editor.\n"
    } > "$tmp"

    $EDITOR "$tmp" < /dev/tty &> /dev/tty || exit "$?"

    rm "$tmp"
    ;;
  recv)
    tmp=$(mktemp 2> /dev/tty)
    mv "$tmp" "$tmp.jsonc"
    tmp="$tmp.jsonc"

    printf "// Paste the received value here, then save and close the editor.\n" > "$tmp"
    $EDITOR "$tmp" < /dev/tty &> /dev/tty

    cat "$tmp"

    rm "$tmp"
    ;;
  *)
    echo "$usage"
    exit 1
    ;;
esac
