#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

usage="Usage: $(basename "$0") <from-email> <to-email> <send|recv>"

if [ $# -lt 3 ]; then
  echo "$usage"
  exit 1
fi

function quotestring {
	echo "${1//\"/\\\"}"
}

from="$1"
email="$2"

case "$3" in
	send)
    sdp=$(cat -)
		osascript <<-EOS
			tell application "Mail"
				set msg to make new outgoing message
				set sender of msg to "$from"
				set subject of msg to "rtc connection details"
				make new recipient at end of to recipients of msg with properties {address:"$email"}
				set content of msg to "$(quotestring "$sdp")"
				send msg
			end tell
		EOS
		;;
	recv)
		sdp=""

		while [ -z "$sdp" ]; do
			tmp=$(osascript -e '
				tell application "Mail"
					set msgs to messages of inbox
					set msg to item 1 of msgs
					sender of msg & "\n" & content of msg
				end tell
			')

			sender=$(echo "$tmp" | head -n 1)
			msg=$(echo "$tmp" | sed '/^$/d' | tail -n +2)

			if [[ "$sender" == *"$email"* ]]; then
				sdp="${msg//$'\n'/\\n}"
			else
				sleep 1
			fi
		done

		echo "$sdp"
		;;
	*)
		echo "$usage"
		exit 1
		;;
esac
